-- Criação do banco de dados (caso ainda não exista)
CREATE DATABASE IF NOT EXISTS ser_sustentavel;
USE ser_sustentavel;

-- 1. TABELA DE USUÁRIOS (Essencial para a Sprint 1)
-- Guarda os dados cadastrais e a senha encriptada de forma segura
CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABELA DE SESSÃO DE LOGIN (Suporte para a Autenticação da Sprint 1)
-- Guarda os tokens ativos para controlar quem está online no sistema
CREATE TABLE IF NOT EXISTS SESSAO_LOGIN (
    ID_SESSAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    TOKEN_SESSAO VARCHAR(255) NOT NULL,
    DATA_HORA_LOGIN DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);
